Change /admin/addproduct to /dashboard
vladstanescu94/ProiectIS pull request #54
Opened 2018-12-29 18:54 UTC by adrianbunea

2018-12-29 19:03 UTC, precupstefan requested changes

2018-12-29 19:03 UTC, precupstefan commented on src/main/java/com/proiect/pos/controller/MainController.java
> +    public ModelAndView getAddProductPage() {
schimba numele functiei. Numele zice ca face ceva, cand defapt face altceva

2018-12-29 19:03 UTC, precupstefan commented on src/main/java/com/proiect/pos/controller/MainController.java
> +    @RequestMapping(value = "dashboard", method = RequestMethod.POST)
Adaugarea de produs nu se face apeland /dashboard. Te rog schimba pe /admin/createNewProduct.

Dupa care dupa ce se executa functia asta faci un redirect inapoi la Dashboard. Un "NEADMIN" n-ar trebui sa aiba acces sa faca post-uri pe aplicatie.

WebSecurity config se ocupa de asta prin `hasAuthority(Admin)`.
Uite aici, poate te ajuta: https://stackoverflow.com/questions/40880772/spring-boot-redirect-to-a-different-controller-method

2018-12-29 19:04 UTC, vladstanescu94 approved these changes

2018-12-29 19:04 UTC, vladstanescu94 commented on src/main/java/com/proiect/pos/controller/MainController.java
> +    public ModelAndView getAddProductPage() {
probabil trebuia rename si aici

2018-12-29 19:13 UTC, adrianbunea commented on src/main/java/com/proiect/pos/controller/MainController.java
> +    public ModelAndView getAddProductPage() {
Intrebare, ca sa fac asta trebuie sa dau commit + push din nou si se modifica si pull request-ul?

2018-12-30 09:54 UTC, precupstefan commented on src/main/java/com/proiect/pos/controller/MainController.java
> +    public ModelAndView getAddProductPage() {
Cred ca da

2019-01-02 16:04 UTC, precupstefan approved these changes

2019-01-02 16:13 UTC, merged